### ISSUE TITLE
Label misalignment

### ISSUE THREAD

**Issue by jared-hughes** [DesModder/DesModder#917]
DesModder off:
![image](https://github.com/user-attachments/assets/247c00da-5f43-4b09-b9b9-66d573f3acf1)

DesModder on:
![image](https://github.com/user-attachments/assets/d7a15a35-2cc5-457d-bc23-56e4050191c3)

There's a new CSS entry that may be relevant:

```css
.dcg-mixed-text-math .dcg-mq-math-mode .dcg-mq-root-block {
  vertical-align: baseline;
  overflow: visible;
}
```
